### ISSUE TITLE
There should be a FROM variable in the env file

### ISSUE THREAD

**Issue by DiamonndAde** [RajKKapadia/YouTube-WhatsApp-OpenAI#2]
# LIke this
`
FROM:whatsapp:(This is where your twilio number will go into)
`

**Comment by ladoual** [comment]
Hi,
you mean like this:
 FROM:whatsapp=+141552xxxxx

i did everything my not respond back from Whatsapp bot 
do you have any tips ?

**Comment by RajKKapadia** [comment]
Thanks for pointing out, I have updated the readme file...

**Comment by ladoual** [comment]
Thank you for the update, but I am still experiencing an issue with my WhatsApp bot not responding to all text messages. The logs from my local host and Ngrok show a status code of 200, but the Twilio logs are displaying a warning with error code 12200, indicating a schema validation issue. Can you please advise me on how to resolve this problem?
